# Generated by Claude
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('agent', 'Agent'), ('app', 'App'), ('assistant', 'Assistant'), ('automation', 'Automation')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('value_streams', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('eos', 'End of Sale'), ('eol', 'End of Life')], default='draft', max_length=20)),
                ('saleor_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One-time'), ('usage', 'Usage-based')], default='monthly', max_length=20)),
                ('price_credits', models.IntegerField(default=0)),
                ('included_credits', models.IntegerField(default=0)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('saleor_variant_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='offerings.offering')),
            ],
            options={
                'ordering': ['price_credits'],
                'unique_together': {('offering', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='OfferingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(max_length=50)),
                ('artifact_s3_key', models.CharField(max_length=500)),
                ('artifact_sha256', models.CharField(max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('defaults', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='offerings.offering')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('offering', 'version_label')},
            },
        ),
    ]
