# Generated by Claude
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Idempotency records',
            },
        ),
    ]
